[package]
name = "cachers"
version = "0.1.0"
authors = ["Dong Nguyen <nguyenduydong@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
